### ISSUE TITLE
Error when doing `make extract`

### ISSUE THREAD

**Issue by tclune** [michaeltouati/ESVM#10]
I got the following traceback with the latest version of the code.   Apologies if this is due to an additional package that I need to install since my last attempt several weeks ago.

```
bash-3.2$ make extract
python3 sources/extract.py
Energy plot
Traceback (most recent call last):
  File "/Users/tclune/swdev/tmp/ESVM/sources/extract.py", line 77, in <module>
    fig.savefig('figures/energy_log.png',bbox_inches='tight')
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/figure.py", line 3015, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2230, in print_figure
    self.figure.draw(renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/figure.py", line 2790, in draw
    mimage._draw_list_compositing_images(
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 2921, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/axis.py", line 1142, in draw
    ticklabelBoxes, ticklabelBoxes2 = self._get_tick_bboxes(ticks_to_draw,
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/axis.py", line 1068, in _get_tick_bboxes
    return ([tick.label1.get_window_extent(renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/axis.py", line 1068, in <listcomp>
    return ([tick.label1.get_window_extent(renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/text.py", line 903, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/text.py", line 306, in _get_layout
    _, lp_h, lp_d = renderer.get_text_width_height_descent(
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 229, in get_text_width_height_descent
    w, h, d = texmanager.get_text_width_height_descent(
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/texmanager.py", line 401, in get_text_width_height_descent
    page, = dvi
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/dviread.py", line 251, in __iter__
    while self._read():
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/dviread.py", line 331, in _read
    self._dtable[byte](self, byte)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/dviread.py", line 174, in wrapper
    return method(self, *[f(self, byte-min) for f in get_args])
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/dviread.py", line 476, in _fnt_def
    self._fnt_def_real(k, c, s, d, a, l)
  File "/Users/tclune/installed/Core/homebrew/lib/python3.9/site-packages/matplotlib/dviread.py", line 483, in _fnt_def_real
    raise FileNotFoundError("missing font metrics file: %s" % fontname)
FileNotFoundError: missing font metrics file: cmss12
make: *** [extract] Error 1
```

**Comment by tclune** [comment]
Referencing: openjournals/joss-reviews#3618

**Comment by michaeltouati** [comment]
Tell me if it solved the problem. Do you think I have to mention that kind of issue since it is related with a feature of the python package Matplotlib (https://matplotlib.org/stable/tutorials/text/usetex.html)

**Comment by michaeltouati** [comment]
Were you able to fix this problem by checking if LaTeX, dvipng and ghostscript are working on your machine?

**Comment by tclune** [comment]
Sorry - I somehow missed your initial response yesterday afternoon.   Have not looked further into this.   The confusing bit is that this worked for me a few weeks back, and I've not touched my python installation since then as far as I can recall.  I'm updating it now and I'll see if that fixes things.
