### ISSUE TITLE
Floating-point exception when compiled in debug mode

### ISSUE THREAD

**Issue by TomGoffrey** [michaeltouati/ESVM#8]
Having modified the Makefile to compile with debug flags:

```
$ git diff makefile
diff --git a/makefile b/makefile
index 2ee2fed..db00548 100755
--- a/makefile
+++ b/makefile
@@ -30,13 +30,13 @@ F90 = gfortran
 # openMP #
 ##########

-OPTS = -fopenmp -O3 -ffixed-line-length-none  -fdefault-real-8
+#OPTS = -fopenmp -O3 -ffixed-line-length-none  -fdefault-real-8

 #########
 # debug #
 #########

-#OPTS = -g -fopenmp -fbacktrace -ffpe-trap=zero,overflow,underflow
+OPTS = -g -fopenmp -fbacktrace -ffpe-trap=zero,overflow,underflow

 #####################################
 #####################################
```

and running with the input-deck as provided I see floating-point errors:

```
...
 -----------------------------------------
 * Deduced parameters :
 N_x     =          205
 N_vx    =          801
 n0      =    1.0000000000000000E+019
 Te      =    11604258.709350331
 -----------------------------------------

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Backtrace for this error:
#0  0x7f7becf1c2ed in ???
#1  0x7f7becf1b503 in ???
#2  0x7f7bec58203f in ???
#3  0x7f7becbe9ea4 in ???
#4  0x7f7becb721fe in ???
#5  0x55c2128020e5 in __library_MOD_init_simu
	at sources/library.f90:115
#6  0x55c212804e78 in esvm
	at sources/esvm.f90:47
#7  0x55c212805c8a in main
	at sources/esvm.f90:11
Floating point exception (core dumped)
```

**Comment by michaeltouati** [comment]
Issue solved. It was caused by the undeflow debug compiling option
